# =============================================
# Configuración para Render.com - AXXON Operator
# =============================================

services:
  - type: web
    name: axxon-operator
    env: python
    plan: free                   # Tier gratuito (para MVP)
    region: oregon              # Región por defecto
    buildCommand: |
      pip install --upgrade pip setuptools wheel &&
      pip uninstall -y openai &&
      pip install openai==1.16.2 &&
      pip install -r requirements.txt --no-cache-dir
    startCommand: >-
      gunicorn main_orquestador:app
      --timeout 600             # Tiempo para operaciones simbólicas pesadas
      --workers 2               # Optimizado para 512MB RAM
      --threads 4               # Manejo concurrente
      --worker-class gthread   # Para Async I/O
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}       # Desde secrets de Render
      - key: NOTION_TOKEN
        value: ${NOTION_TOKEN}         # Token de integración Notion
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}     # OAuth Google
      - key: GOOGLE_CLIENT_SECRET
        value: ${GOOGLE_CLIENT_SECRET} # Secret de Google
      - key: REDIRECT_URI
        value: ${REDIRECT_URI}         # URL de callback OAuth
      - key: PYTHON_VERSION
        value: 3.11.9                   # Versión fija para estabilidad
      - key: FAISS_OPTIMIZED
        value: "avx2"                   # Optimización FAISS para CPUs modernas
      - key: AXXON_ENV
        value: production              # Entorno simbólico activo